# Generated by Django 2.0.5 on 2018-05-21 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('black', models.IntegerField(default=1)),
                ('difficulty', models.IntegerField(default=0)),
                ('board', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR')),
                ('turn', models.CharField(default='w', max_length=1)),
                ('castling', models.CharField(default='KQkq', max_length=4)),
                ('enPassant', models.CharField(default='-', max_length=4)),
                ('halfMove', models.IntegerField(default=0)),
                ('fullMove', models.IntegerField(default=1)),
                ('isOver', models.BooleanField(default=False)),
                ('message', models.TextField(default='')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
